# Generated by Django 5.2.7 on 2025-10-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payment", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="proccessed_at",
            new_name="processed_at",
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("stripe", "Stripe"),
                    ("paypal", "PayPal"),
                    ("manual", "Manual"),
                ],
                default="stripe",
                max_length=20,
            ),
        ),
    ]
