# Generated by Django 5.2.7 on 2025-10-11 07:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("movies", "0002_remove_movie_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_favorites",
                "ordering": ["-created_at"],
                "unique_together": {("user", "movie")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="favorite_movies",
            field=models.ManyToManyField(
                blank=True,
                related_name="fans",
                through="accounts.Favorite",
                to="movies.movie",
            ),
        ),
        migrations.CreateModel(
            name="Watched",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_position_sec", models.PositiveIntegerField(default=0)),
                ("duration_sec", models.PositiveIntegerField(default=0)),
                ("progress_percent", models.PositiveSmallIntegerField(default=0)),
                ("finished", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("watched_at", models.DateTimeField(auto_now=True)),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="movies.movie"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_watched",
                "ordering": ["-watched_at"],
                "unique_together": {("user", "movie")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="watched_movies",
            field=models.ManyToManyField(
                blank=True,
                related_name="watchers",
                through="accounts.Watched",
                to="movies.movie",
            ),
        ),
    ]
