# Generated by Django 5.2.7 on 2025-10-17 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_favorite_user_favorite_movies_watched_and_more"),
        ("subscribe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscription",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="current_user",
                to="subscribe.subscription",
            ),
        ),
    ]
