# Generated by Django 5.2.7 on 2025-10-31 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscribe", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True, default=None, max_length=255, null=True, unique=True
            ),
        ),
    ]
