# Generated by Django 5.2.7 on 2025-10-11 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="likes",
        ),
    ]
