# Generated by Django 5.2.7 on 2025-10-28 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0003_actor"),
    ]

    operations = [
        migrations.CreateModel(
            name="MovieCharacter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=100, unique=True)),
            ],
            options={
                "db_table": "movie_characters",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="actor",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/actors/"),
        ),
        migrations.AlterField(
            model_name="author",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="avatars/authors/"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="movies/posters/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="movies/videos"),
        ),
        migrations.CreateModel(
            name="Casting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit_order", models.PositiveIntegerField(default=0)),
                ("is_voice", models.BooleanField(default=False)),
                ("is_cameo", models.BooleanField(default=False)),
                ("notes", models.CharField(blank=True, max_length=255)),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="castings",
                        to="movies.actor",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cast",
                        to="movies.movie",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="appearances",
                        to="movies.moviecharacter",
                    ),
                ),
            ],
            options={
                "db_table": "casting",
                "ordering": ["movie", "credit_order"],
                "unique_together": {("movie", "character", "actor")},
            },
        ),
        migrations.AddField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                blank=True,
                related_name="movies",
                through="movies.Casting",
                to="movies.actor",
            ),
        ),
        migrations.AddField(
            model_name="movie",
            name="characters",
            field=models.ManyToManyField(
                blank=True,
                related_name="movies",
                through="movies.Casting",
                to="movies.moviecharacter",
            ),
        ),
    ]
