# Generated by Django 5.2.7 on 2025-10-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0004_moviecharacter_alter_actor_avatar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="duration",
            field=models.DurationField(blank=True, null=True),
        ),
    ]
