# Generated by Django 5.2.7 on 2025-10-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0005_movie_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="last_meta_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="movie",
            name="meta_dirty",
            field=models.BooleanField(default=False),
        ),
    ]
