# Generated by Django 5.2.7 on 2025-10-31 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0006_movie_last_meta_update_movie_meta_dirty"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="duration",
        ),
    ]
